### ISSUE TITLE
Example code working on Linux but not working on Windows Pycharm

### ISSUE THREAD

**Issue by UcanYusuf** [thecognifly/YAMSPy#7]
Hello, the example code working on linux but I am getting this error on windows:

![Ekran Alıntısı](https://user-images.githubusercontent.com/68384469/96756844-4e762d80-13dd-11eb-9702-2bf3d748ed0c.PNG)

İs there a solution for windows? Thank you.

**Comment by ricardodeazambuja** [comment]
Ok, I pushed a new version that should work with windows. Please, reinstall and test it ;)
```
pip3 install git+git://github.com/ricardodeazambuja/yamspy --upgrade
```

**Comment by UcanYusuf** [comment]
> Ok, I pushed a new version that should work with windows. Please, reinstall and test it ;)
> 
> ```
> pip3 install git+git://github.com/ricardodeazambuja/yamspy --upgrade
> ```
> 
> You may need to install a special version of [curses](https://docs.python.org/3/library/curses.html) to use the [simpleUI.py](https://github.com/thecognifly/YAMSPy/blob/0eda0abb673dcf949f3cf7da880e18b7cd817776/Examples/simpleUI.py#L48) on windows:
> https://pypi.org/project/windows-curses/

İt is working now. Thank you very much. You are awesome 👍
